<a href="https://colab.research.google.com/github/Akbhartiq/TensorFlow/blob/master/Day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [4]:
x=tf.constant(4)
print(x)

x=tf.constant(4.2,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[4.2]], shape=(1, 1), dtype=float32)


In [6]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
x=tf.ones((2,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
x=tf.zeros((4,2,3)) #How to interpret 3D matrix , it's like 4 2x3 matrix
print(x)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(4, 2, 3), dtype=float32)


In [10]:
# Method to get the Identity Matrix
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [12]:
# Random-Normal
x=tf.random.normal((3,3),mean=0,stddev=1)
print(x)

#Random-Uniform
x=tf.random.uniform((2,3),minval=2,maxval=5)
print(x)

#Range-Function
x=tf.range(9)
print(x)

#Another range
x=tf.range(start=4,limit=10,delta=0.5)
print(x)

tf.Tensor(
[[ 1.7272259  -0.37571013  0.20842856]
 [ 0.43500155  0.17465574  0.3313994 ]
 [ 0.9815043   1.5040603  -0.9475344 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3.4773612 4.3188868 3.6962268]
 [2.070146  3.4890137 4.609383 ]], shape=(2, 3), dtype=float32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5], shape=(12,), dtype=float32)


In [13]:
# cast function to change the data-Type
x=tf.cast(x,dtype=tf.float64)
print(x)

tf.Tensor([4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5], shape=(12,), dtype=float64)


In [14]:
# different dtype
'''tf.float(16,32,64) and tf.int(8,16,32,64) and tf.bool'''

'tf.float(16,32,64) and tf.int(8,16,32,64) and tf.bool'

In [43]:
# Mathematical Operations on the Tensors
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])
print(x)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([9 8 7], shape=(3,), dtype=int32)


In [17]:
print(x+y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [18]:
#or
z=tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [19]:
# Subtract , can use tf.subtract()
z=x-y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [20]:
#Element wise division
z=x/y
z=tf.divide(x,y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [22]:
# Element wise multiplication
z=x*y
z=tf.multiply(x,y)
print(z)


tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [44]:
#Dot product
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [24]:
# Another method to find the dot product
z=tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [27]:
# Element wise operations
x=tf.constant([1,2,3])
z=x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [28]:
# Matrix Multiplication
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
z=tf.matmul(x,y)
print(z)
z=x @ y
print(z)


tf.Tensor(
[[ 0.6398915  -2.1781814   2.5809731   0.84537756]
 [ 0.07224414  0.37747103  1.3597862   1.5517019 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.6398915  -2.1781814   2.5809731   0.84537756]
 [ 0.07224414  0.37747103  1.3597862   1.5517019 ]], shape=(2, 4), dtype=float32)


In [33]:
# Indexing concept
x=tf.constant([0,1,2,9,4,5,6])
print(x)
print(x[:])
print(x[1:])
print(x[1:3])

tf.Tensor([0 1 2 9 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([0 1 2 9 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([1 2 9 4 5 6], shape=(6,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [34]:
print(x[::2])#skipping every next element

tf.Tensor([0 2 4 6], shape=(4,), dtype=int32)


In [36]:
# understanding tf.gether
indices=tf.constant(3)
z=tf.gather(x,indices)
print(z)

tf.Tensor(9, shape=(), dtype=int32)


In [37]:
# Indexing in 2D matrix
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])
print(x[0:2,:])
print(x[0::2,1:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2]
 [6]], shape=(2, 1), dtype=int32)


In [39]:
# Welcome to the Concept of the Reshaping
x=tf.range(9)
print(x)

x=tf.reshape(x,(  3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [40]:
# Getting Transpose
x=tf.range(12)
x=tf.reshape(x,(3,4))
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]], shape=(4, 3), dtype=int32)
